Repository LJIEUN/evenly-back, pull requests merged in 2025-03, with the labels that each got.

#2 init: 프로젝트 셋팅, 도커 컴포즈 추가, 개발 db 연결, 구조 셋팅
  .env.example
  .gitattributes
  .gitignore
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/codeisevenlycooked/evenly/EvenlyApplication.java
  src/main/java/com/codeisevenlycooked/evenly/config/CommonConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/SignUpDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/User.java
  src/main/java/com/codeisevenlycooked/evenly/global/ApiResponse.java
  src/main/java/com/codeisevenlycooked/evenly/repository/UserRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/AuthService.java
  src/main/resources/application-example.yml
  src/test/java/com/codeisevenlycooked/evenly/EvenlyApplicationTests.java
Labels: 🎉init

#1 Create pull_request_template.md
  docs/pull_request_template.md
Labels: 📝documentation

#4 회원가입 API 구현
  Dockerfile
  build.gradle
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/SignUpDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/User.java
  src/main/java/com/codeisevenlycooked/evenly/entity/UserRole.java
  src/main/java/com/codeisevenlycooked/evenly/entity/UserStatus.java
  src/main/java/com/codeisevenlycooked/evenly/mock/HealthCheckController.java
  src/main/java/com/codeisevenlycooked/evenly/repository/UserRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/AuthService.java
  src/main/resources/application-example.yml
  src/test/java/com/codeisevenlycooked/evenly/service/AuthServiceTest.java
Labels: ✨feature, 🔧config

#6 회원 정보 조회, 회원 정보 수정, 탈퇴, 휴면 계정 처리 기능 구현
  src/main/java/com/codeisevenlycooked/evenly/EvenlyApplication.java
  src/main/java/com/codeisevenlycooked/evenly/controller/UserController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/UpdatePasswordDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/UserInfoDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/User.java
  src/main/java/com/codeisevenlycooked/evenly/global/scheduler/UserCleanupScheduler.java
  src/main/java/com/codeisevenlycooked/evenly/repository/UserRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/AuthService.java
  src/main/java/com/codeisevenlycooked/evenly/service/UserService.java
Labels: ✨feature

#7 상품 목록 및 상품 상세 기능 구현
  src/main/java/com/codeisevenlycooked/evenly/controller/ProductController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/ProductResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Product.java
  src/main/java/com/codeisevenlycooked/evenly/entity/ProductStatus.java
  src/main/java/com/codeisevenlycooked/evenly/repository/ProductRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/data.sql
  src/test/java/com/codeisevenlycooked/evenly/service/ProductServiceTest.java
Labels: ✨feature

#8 Feat/admin/products
  build.gradle
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminProductController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/AdminProductDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Product.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/data.sql
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/templates/admin/home.html
  src/main/resources/templates/admin/layout.html
  src/main/resources/templates/admin/product-form.html
  src/main/resources/templates/admin/products.html
Labels: ✨feature, ♻️refactoring, 🔧config

#9 주문 생성, 조회 API 구현
  src/main/java/com/codeisevenlycooked/evenly/config/security/JwtUtil.java
  src/main/java/com/codeisevenlycooked/evenly/controller/OrderController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/UserController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderItemDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderItemResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderItem.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderStatus.java
  src/main/java/com/codeisevenlycooked/evenly/entity/PaymentMethod.java
  src/main/java/com/codeisevenlycooked/evenly/repository/OrderItemRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/OrderRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/test/java/com/codeisevenlycooked/evenly/service/OrderServiceTest.java
Labels: ✨feature

#10 상품 페이지네이션 및 카테고리 쿼리 추가
  src/main/java/com/codeisevenlycooked/evenly/config/CategoryInitializer.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminProductController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/ProductController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/AdminProductDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/PagedProductResponse.java
  src/main/java/com/codeisevenlycooked/evenly/dto/ProductResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Category.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Product.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CategoryRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/ProductRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/data.sql
  src/main/resources/templates/admin/product-form.html
  src/main/resources/templates/admin/products.html
Labels: ✨feature

#11 결제 API 구현
  src/main/java/com/codeisevenlycooked/evenly/controller/OrderController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/PaymentController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/PaymentRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderStatus.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Payment.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Product.java
  src/main/java/com/codeisevenlycooked/evenly/repository/OrderRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/PaymentRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/java/com/codeisevenlycooked/evenly/service/PaymentService.java
Labels: 🐛bug, ✨feature

#12 CORS 설정 및 이미지 프록시 적용
  src/main/java/com/codeisevenlycooked/evenly/config/AppConfig.java
  src/main/java/com/codeisevenlycooked/evenly/config/WebConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/image/ImageController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/ProductResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/mock/MockProductController.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/application-example.yml
Labels: 🔧config

#13 서버 배포용 도커 컴포즈 파일 수정
  docker-compose.yml
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/templates/admin/layout.html
Labels: 🔧config

#15 예외 처리 및 버그 수정
  src/main/java/com/codeisevenlycooked/evenly/config/CategoryInitializer.java
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/image/ImageController.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/ErrorResponse.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeisevenlycooked/evenly/mock/MockProductController.java
  src/main/java/com/codeisevenlycooked/evenly/service/AuthService.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/java/com/codeisevenlycooked/evenly/service/UserService.java
  src/main/resources/application-example.yml
  src/main/resources/templates/admin/products.html
Labels: 🐛bug, 🔧config

#16 장바구니 기능 구현 및 JWT 기반 인증 방식 적용
  src/main/java/com/codeisevenlycooked/evenly/controller/CartController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/CartItemDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/CartItemResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/CartResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Cart.java
  src/main/java/com/codeisevenlycooked/evenly/entity/CartItem.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CartItemRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CartRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/CartService.java
Labels: ✨feature, ♻️refactoring

#17 로그인 응답 변경 + 예외처리 + 이미지 프록시 삭제
  src/main/java/com/codeisevenlycooked/evenly/config/security/JwtUtil.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/TokenResponse.java
Labels: 🐛bug

#19 250326 배포 - 장바구니, 이미지 프록시 삭제, 로그인 결과 반환 방식 변경
  src/main/java/com/codeisevenlycooked/evenly/config/CategoryInitializer.java
  src/main/java/com/codeisevenlycooked/evenly/config/security/JwtUtil.java
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/CartController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/image/ImageController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/CartItemDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/CartItemResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/CartResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/TokenResponse.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Cart.java
  src/main/java/com/codeisevenlycooked/evenly/entity/CartItem.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/ErrorResponse.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeisevenlycooked/evenly/mock/MockProductController.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CartItemRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CartRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/AuthService.java
  src/main/java/com/codeisevenlycooked/evenly/service/CartService.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/java/com/codeisevenlycooked/evenly/service/UserService.java
  src/main/resources/application-example.yml
  src/main/resources/templates/admin/products.html
Labels: 🐛bug, ✨feature, ♻️refactoring

#24 버그 3가지 수정
  src/main/java/com/codeisevenlycooked/evenly/dto/ProductResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/data.sql
Labels: 🐛bug

#25 250327 배포 - 주문 결제 통합 API 배포
  src/main/java/com/codeisevenlycooked/evenly/controller/CartController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/OrderController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/PaymentController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/ItemDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderCreationResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderItemDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderItemResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/PaymentRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/dto/ProductResponseDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderItem.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderStatus.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Payment.java
  src/main/java/com/codeisevenlycooked/evenly/global/scheduler/UserCleanupScheduler.java
  src/main/java/com/codeisevenlycooked/evenly/repository/OrderRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/PaymentRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/CartService.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/java/com/codeisevenlycooked/evenly/service/PaymentService.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/resources/data.sql
  src/test/java/com/codeisevenlycooked/evenly/service/OrderServiceTest.java
Labels: 🐛bug, ✨feature

#30 장바구니 수량 버그, 결제시 장바구니 상품 자동삭제 기능 추가, 결제시 재고 변화 에러, CORS 에러 처리
  src/main/java/com/codeisevenlycooked/evenly/config/WebConfig.java
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminUserController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/ProductController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/UserController.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Product.java
  src/main/java/com/codeisevenlycooked/evenly/entity/User.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeisevenlycooked/evenly/mock/HealthCheckController.java
  src/main/java/com/codeisevenlycooked/evenly/mock/MockProductController.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CartItemRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/CartService.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/java/com/codeisevenlycooked/evenly/service/UserService.java
Labels: 🐛bug, ✨feature

#33 유효성 검사 애노테이션 추가
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminUserController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/CartController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/OrderController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Cart.java
  src/main/java/com/codeisevenlycooked/evenly/repository/OrderRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
Labels: 🐛bug

#31 250328 배포 - 장바구니, 결제 버그 수정, 결제-장바구니 자동 삭제 기능 추가, 시큐리티 필터 CORS 허용, 유효성 검사 추가
  src/main/java/com/codeisevenlycooked/evenly/config/WebConfig.java
  src/main/java/com/codeisevenlycooked/evenly/config/security/SecurityConfig.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminUserController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/CartController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/OrderController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/ProductController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/UserController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/OrderRequestDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Cart.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Product.java
  src/main/java/com/codeisevenlycooked/evenly/entity/User.java
  src/main/java/com/codeisevenlycooked/evenly/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeisevenlycooked/evenly/mock/HealthCheckController.java
  src/main/java/com/codeisevenlycooked/evenly/mock/MockProductController.java
  src/main/java/com/codeisevenlycooked/evenly/repository/CartItemRepository.java
  src/main/java/com/codeisevenlycooked/evenly/repository/OrderRepository.java
  src/main/java/com/codeisevenlycooked/evenly/service/CartService.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/java/com/codeisevenlycooked/evenly/service/ProductService.java
  src/main/java/com/codeisevenlycooked/evenly/service/UserService.java
Labels: 🐛bug, ✨feature, 🔧config

#35 응답 형식 String text -> Json 변경
  src/main/java/com/codeisevenlycooked/evenly/controller/AuthController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/CartController.java
  src/main/java/com/codeisevenlycooked/evenly/controller/UserController.java
  src/main/java/com/codeisevenlycooked/evenly/global/MessageResponse.java
Labels: 🐛bug

#36 관리자 주문 관리 기능 구현
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminOrderController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/AdminListDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderStatus.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/resources/templates/admin/order-form.html
  src/main/resources/templates/admin/orders.html
Labels: ✨feature, ♻️refactoring

#37 20250328 배포 - 관리자페이지 주문 관리 추가
  src/main/java/com/codeisevenlycooked/evenly/controller/AdminOrderController.java
  src/main/java/com/codeisevenlycooked/evenly/dto/AdminListDto.java
  src/main/java/com/codeisevenlycooked/evenly/entity/Order.java
  src/main/java/com/codeisevenlycooked/evenly/entity/OrderStatus.java
  src/main/java/com/codeisevenlycooked/evenly/service/OrderService.java
  src/main/resources/templates/admin/order-form.html
  src/main/resources/templates/admin/orders.html
Labels: ✨feature
